//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CustomerManagementModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CustomerManagementEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CustomerManagementEntities object using the connection string found in the 'CustomerManagementEntities' section of the application configuration file.
        /// </summary>
        public CustomerManagementEntities() : base("name=CustomerManagementEntities", "CustomerManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CustomerManagementEntities object.
        /// </summary>
        public CustomerManagementEntities(string connectionString) : base(connectionString, "CustomerManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CustomerManagementEntities object.
        /// </summary>
        public CustomerManagementEntities(EntityConnection connection) : base(connection, "CustomerManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Country> Countries
        {
            get
            {
                if ((_Countries == null))
                {
                    _Countries = base.CreateObjectSet<Country>("Countries");
                }
                return _Countries;
            }
        }
        private ObjectSet<Country> _Countries;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Countries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCountries(Country country)
        {
            base.AddObject("Countries", country);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerManagementModel", Name="Country")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Country : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Country object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="dialingCountryCode">Initial value of the DialingCountryCode property.</param>
        /// <param name="internationalDialingCode">Initial value of the InternationalDialingCode property.</param>
        /// <param name="internetTLD">Initial value of the InternetTLD property.</param>
        public static Country CreateCountry(global::System.Guid id, global::System.String name, global::System.String dialingCountryCode, global::System.String internationalDialingCode, global::System.String internetTLD)
        {
            Country country = new Country();
            country.ID = id;
            country.Name = name;
            country.DialingCountryCode = dialingCountryCode;
            country.InternationalDialingCode = internationalDialingCode;
            country.InternetTLD = internetTLD;
            return country;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNoFormat
        {
            get
            {
                return _PhoneNoFormat;
            }
            set
            {
                OnPhoneNoFormatChanging(value);
                ReportPropertyChanging("PhoneNoFormat");
                _PhoneNoFormat = StructuralObject.SetValidValue(value, true, "PhoneNoFormat");
                ReportPropertyChanged("PhoneNoFormat");
                OnPhoneNoFormatChanged();
            }
        }
        private global::System.String _PhoneNoFormat;
        partial void OnPhoneNoFormatChanging(global::System.String value);
        partial void OnPhoneNoFormatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DialingCountryCode
        {
            get
            {
                return _DialingCountryCode;
            }
            set
            {
                OnDialingCountryCodeChanging(value);
                ReportPropertyChanging("DialingCountryCode");
                _DialingCountryCode = StructuralObject.SetValidValue(value, false, "DialingCountryCode");
                ReportPropertyChanged("DialingCountryCode");
                OnDialingCountryCodeChanged();
            }
        }
        private global::System.String _DialingCountryCode;
        partial void OnDialingCountryCodeChanging(global::System.String value);
        partial void OnDialingCountryCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InternationalDialingCode
        {
            get
            {
                return _InternationalDialingCode;
            }
            set
            {
                OnInternationalDialingCodeChanging(value);
                ReportPropertyChanging("InternationalDialingCode");
                _InternationalDialingCode = StructuralObject.SetValidValue(value, false, "InternationalDialingCode");
                ReportPropertyChanged("InternationalDialingCode");
                OnInternationalDialingCodeChanged();
            }
        }
        private global::System.String _InternationalDialingCode;
        partial void OnInternationalDialingCodeChanging(global::System.String value);
        partial void OnInternationalDialingCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InternetTLD
        {
            get
            {
                return _InternetTLD;
            }
            set
            {
                OnInternetTLDChanging(value);
                ReportPropertyChanging("InternetTLD");
                _InternetTLD = StructuralObject.SetValidValue(value, false, "InternetTLD");
                ReportPropertyChanged("InternetTLD");
                OnInternetTLDChanged();
            }
        }
        private global::System.String _InternetTLD;
        partial void OnInternetTLDChanging(global::System.String value);
        partial void OnInternetTLDChanged();

        #endregion

    }

    #endregion

}
