//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyWcfService")]
    public interface IMyWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWcfService/CountryByCode", ReplyAction="http://tempuri.org/IMyWcfService/CountryByCodeResponse")]
        string CountryByCode(string isoCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWcfService/CountryByCode", ReplyAction="http://tempuri.org/IMyWcfService/CountryByCodeResponse")]
        System.Threading.Tasks.Task<string> CountryByCodeAsync(string isoCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyWcfServiceChannel : WpfAppClient.ServiceReference1.IMyWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWcfServiceClient : System.ServiceModel.ClientBase<WpfAppClient.ServiceReference1.IMyWcfService>, WpfAppClient.ServiceReference1.IMyWcfService {
        
        public MyWcfServiceClient() {
        }
        
        public MyWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CountryByCode(string isoCode) {
            return base.Channel.CountryByCode(isoCode);
        }
        
        public System.Threading.Tasks.Task<string> CountryByCodeAsync(string isoCode) {
            return base.Channel.CountryByCodeAsync(isoCode);
        }
    }
}
